---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-eks3
  region: us-east-1

vpc:
  id:
  cidr: "10.0.0.0/21"
  subnets:
    public:
      public-one:
        id:
        cidr: "10.0.1.0/24"
      public-two:
        id:
        cidr: "10.0.2.0/24"
nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: false
